image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  - name: localhost webApp
    port: 4200
    onOpen: open-browser
    visibility: public
  - name: gitpod
    port: 5900
    onOpen: ignore
    visibility: public
  - name: gitpod
    port: 6080
    onOpen: ignore
    visibility: public
  - name: gitpod
    port: 1123
    onOpen: ignore
    visibility: public
  - name: gitpod
    port: 49152
    onOpen: ignore
    visibility: public

# Tarefas na Inicialização
tasks:
  - name: Start front-end
    before: export NG_CLI_ANALYTICS=ci
    init: echo n | npm i -g @angular/cli@17 && npm i -g commitizen
    command: npm ci && npm run start
