image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  - name: localhost webApp
    port: 4200
    onOpen: open-browser
    visibility: public
  - name: gitpod
    port: 5900
    onOpen: ignore
    visibility: public
  - name: gitpod
    port: 6080
    onOpen: ignore
    visibility: public
  - name: gitpod
    port: 1123
    onOpen: ignore
    visibility: public
  - name: gitpod
    port: 49152
    onOpen: ignore
    visibility: public

# Tarefas na Inicialização
tasks:
  - name: Start front-end
    before: export NG_CLI_ANALYTICS=ci
    init: echo n | npm i -g @angular/cli@17 && npm i -g commitizen jest
    command: npm ci && npm run start

vscode:
  extensions:
    - Mikael.Angular-BeastCode
    - Angular.ng-template
    - cyrilletuzi.angular-schematics
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - MohammadBaqer.better-folding
    - streetsidesoftware.code-spell-checker-portuguese-brazilian
    - streetsidesoftware.code-spell-checker-british-english
    - streetsidesoftware.code-spell-checker
    - ms-azuretools.vscode-docker
    - EditorConfig.EditorConfig
    - Tobermory.es6-string-html
    - dbaeumer.vscode-eslint
    - donjayamanne.githistory
    - github.vscode-github-actions
    - eamodio.gitlens
    - ecmel.vscode-html-css
    - xabikos.JavaScriptSnippets
    - humao.rest-client
    - SonarSource.sonarlint-vscode
    - shardulm94.trailing-spaces
    - vscode-icons-team.vscode-icons
