name: Lighthouse

on:
  pull_request:
    branches: [master]

jobs:
  lighthouse_job:  # ID único do job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://martins86.github.io/tmf-angular-lab/
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
